# Find all
GET http://localhost:8080/words/

# Find by id
GET http://localhost:8080/words/1


# Delete by id
DELETE  http://localhost:8080/words/4

# Post new word
POST http://localhost:8080/words/
Content-type: application/json

{"fin": "Auto",
"eng": "Car"}
